apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: s2i-nodejs-run
spec:
  taskRef:
    name: source-to-image
  serviceAccount: s2i-build-robot
  inputs:
    params:
    - name: Source
      value: https://github.com/nodeshift-starters/nodejs-rest-http
    - name: Builder
      value: nodeshift/centos7-s2i-nodejs:latest
    - name: ImageOutput
      value: quay.io/chmouel/tekton-s2i-nodejs-example
  trigger:
    type: manual
