apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: s2i-java-run
spec:
  taskRef:
    name: s2i-task-java
  serviceAccount: s2i-build-robot
  inputs:
    params:
    - name: Source
      value: https://github.com/vorburger/s2i-java-example
    - name: ImageOutput
      value: quay.io/chmouel/tekton-s2i-java-example
  trigger:
    type: manual
